server:
  port: 4042

spring:
  application:
    name: user-interface
  zipkin:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4001/eureka

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 60
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      registerCb:
        base-config: shared

